In [ ]:
import numpy as np

X = np.load('X_features.npy')
y = np.load('y_labels.npy')

[[1.         1.         1.         ... 0.25       0.1        0.0078125 ]
 [1.         1.         1.         ... 0.26315789 0.08333333 0.5       ]
 [1.         1.         1.         ... 0.26829268 0.         0.02439024]
 ...
 [1.         1.         1.         ... 1.         1.         1.        ]
 [1.         1.         1.         ... 0.51162791 0.22222222 1.        ]
 [1.         1.         1.         ... 1.         1.         1.        ]]
[0 1 0 ... 1 1 1]


In [3]:
X

array([[1.        , 1.        , 1.        , ..., 0.25      , 0.1       ,
        0.0078125 ],
       [1.        , 1.        , 1.        , ..., 0.26315789, 0.08333333,
        0.5       ],
       [1.        , 1.        , 1.        , ..., 0.26829268, 0.        ,
        0.02439024],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 0.51162791, 0.22222222,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ]], shape=(4733394, 25))

In [4]:
y

array([0, 1, 0, ..., 1, 1, 1], shape=(4733394,))